import type { NextRequest } from "next/server"
import type { Prisma } from "@/lib/generated/prisma/client"
import { decimal, pharmacyOk, withPharmacy } from "@/lib/pharmacy"
import { prisma } from "@/lib/prisma"

export async function GET(request: NextRequest) {
  return withPharmacy(request, async (actor) => {
    const params = request.nextUrl.searchParams; const dateFrom = params.get("dateFrom"); const dateTo = params.get("dateTo"); const medicationId = params.get("medicationId"); const movementType = params.get("movementType"); const pharmacistId = params.get("pharmacistId"); const range = { ...(dateFrom ? { gte: new Date(`${dateFrom}T00:00:00.000Z`) } : {}), ...(dateTo ? { lte: new Date(`${dateTo}T23:59:59.999Z`) } : {}) }
    const dispensingWhere: Prisma.DispensingWhereInput = { patient: { registeredFacilityId: actor.facilityId }, ...(Object.keys(range).length ? { createdAt: range } : {}), ...(pharmacistId ? { dispensedById: pharmacistId } : {}), ...(medicationId ? { items: { some: { medicationId } } } : {}) }
    const movementWhere: Prisma.StockMovementWhereInput = { stock: { facilityId: actor.facilityId }, ...(Object.keys(range).length ? { createdAt: range } : {}), ...(medicationId ? { medicationId } : {}), ...(movementType ? { type: movementType as never } : {}) }
    const [prescriptions, dispensings, movements, stocks] = await Promise.all([prisma.prescription.findMany({ where: { patient: { registeredFacilityId: actor.facilityId }, ...(Object.keys(range).length ? { createdAt: range } : {}) }, include: { items: true }, take: 1000 }), prisma.dispensing.findMany({ where: dispensingWhere, include: { items: { include: { medication: true } }, dispensedBy: true, patient: true, prescription: true }, orderBy: { createdAt: "desc" }, take: 1000 }), prisma.stockMovement.findMany({ where: movementWhere, include: { medication: true, stock: true, performedBy: true }, orderBy: { createdAt: "desc" }, take: 1000 }), prisma.medicationStock.findMany({ where: { facilityId: actor.facilityId }, include: { medication: true }, take: 1000 })])
    const daily = new Map<string, number>(); for (const row of dispensings) { const day = (row.dispensedAt ?? row.createdAt).toISOString().slice(0, 10); daily.set(day, (daily.get(day) ?? 0) + row.items.reduce((sum, item) => sum + item.quantityDispensed, 0)) }
    return pharmacyOk({ summary: { totalPrescriptions: prescriptions.length, totalDispensingRecords: dispensings.length, medicinesDispensed: dispensings.flatMap((item) => item.items).reduce((sum, item) => sum + item.quantityDispensed, 0), partialDispensingCount: dispensings.filter((item) => item.status === "PARTIAL").length, lowStockCount: stocks.filter((item) => item.quantityOnHand <= item.medication.reorderLevel).length, expiredStockCount: stocks.filter((item) => item.expiryDate && item.expiryDate < new Date()).length, stockMovementCount: movements.length, stockValuation: stocks.reduce((sum, item) => sum + item.quantityOnHand * (decimal(item.unitCost) ?? 0), 0) }, trend: [...daily.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([date, quantity]) => ({ date, quantity })), recentDispensing: dispensings.slice(0, 25).map((row) => ({ id: row.id, dispenseNo: row.dispenseNo, patientName: `${row.patient.firstName} ${row.patient.lastName}`, pharmacistName: row.dispensedBy?.name ?? null, status: row.status, quantity: row.items.reduce((sum, item) => sum + item.quantityDispensed, 0), dispensedAt: row.dispensedAt?.toISOString() ?? null })), movements: movements.slice(0, 25).map((row) => ({ id: row.id, medicationName: row.medication.name, batchNumber: row.stock.batchNumber, type: row.type, quantity: row.quantity, createdAt: row.createdAt.toISOString() })) })
  })
}
