import type { NextRequest } from "next/server"
import { z } from "zod"
import { pharmacyOk, withPharmacy, writePharmacyAuditLog } from "@/lib/pharmacy"
import { AuditAction } from "@/lib/generated/prisma/enums"
import { prisma } from "@/lib/prisma"

const schema = z.object({ type: z.string().trim().min(1).default("PHARMACY"), dateFrom: z.string().date().nullable().optional(), dateTo: z.string().date().nullable().optional(), medicationId: z.string().nullable().optional(), category: z.string().nullable().optional(), movementType: z.string().nullable().optional(), pharmacistId: z.string().nullable().optional() })
export async function POST(request: NextRequest) { return withPharmacy(request, async (actor) => { const parsed = schema.safeParse(await request.json()); if (!parsed.success) return Response.json({ success: false, message: "Report export filters are invalid." }, { status: 400 }); const rowCount = await prisma.dispensing.count({ where: { patient: { registeredFacilityId: actor.facilityId }, ...(parsed.data.dateFrom || parsed.data.dateTo ? { createdAt: { ...(parsed.data.dateFrom ? { gte: new Date(`${parsed.data.dateFrom}T00:00:00.000Z`) } : {}), ...(parsed.data.dateTo ? { lte: new Date(`${parsed.data.dateTo}T23:59:59.999Z`) } : {}) } } : {}) } }); const record = await prisma.$transaction(async (tx) => { const created = await tx.reportExport.create({ data: { type: "PHARMACY", title: `Pharmacy ${parsed.data.type.toLowerCase()} report ${new Date().toISOString().slice(0, 10)}`, facilityId: actor.facilityId, generatedById: actor.id, parameters: parsed.data, rowCount, status: "REQUESTED", dateFrom: parsed.data.dateFrom ? new Date(`${parsed.data.dateFrom}T00:00:00.000Z`) : null, dateTo: parsed.data.dateTo ? new Date(`${parsed.data.dateTo}T23:59:59.999Z`) : null } }); await writePharmacyAuditLog({ client: tx, request, actor, action: AuditAction.EXPORT, entityType: "ReportExport", entityId: created.id, description: `Requested pharmacy report export with ${rowCount} dispensing rows`, after: { filters: parsed.data, rowCount } }); return created }); return pharmacyOk({ id: record.id, title: record.title, status: record.status, rowCount: record.rowCount, generatedAt: record.generatedAt.toISOString() }, "Export request recorded.", 201) }) }

