"use client"

import { useState } from "react"
import { PackagePlus, Plus, RotateCcw, TriangleAlert } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { DataTable, EmptyState, ErrorPanel, LoadingPanel, Modal, PageHeader, Panel, StatusBadge, controlClass, formatDate, money, td } from "@/components/pharmacy/pharmacy-ui"
import { useCreateMedication, useCreateMovement, useCreateReorder, useCreateStock, useExpiredStock, useLowStock, useMedications, useStock, useStockMovements, useUpdateMedication, useUpdateReorder, useWriteOffStock } from "@/services/pharmacy/pharmacy"
import type { MedicationCatalogItem, MedicationCreatePayload, MedicationStockItem } from "@/types/pharmacy"

const blankMedication: MedicationCreatePayload = { code: null, name: "", genericName: null, category: null, dosageForm: null, strength: null, unit: null, reorderLevel: 0, isActive: true }
function ErrorMessage({ error }: { error: Error | null }) { return error ? <p className="rounded bg-red-50 p-3 text-sm text-red-800">{error.message}</p> : null }

export function MedicationsPage() {
  const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [form, setForm] = useState<MedicationCreatePayload>(blankMedication)
  const query = useMedications({ search, pageSize: 100 }); const create = useCreateMedication()
  async function submit(event: React.FormEvent) { event.preventDefault(); await create.mutateAsync(form); setForm(blankMedication); setOpen(false) }
  return <><PageHeader title="Medication catalog" description="Facility-owned medication definitions available to clinicians and pharmacy stock." actions={<Button onClick={() => setOpen(true)}><Plus />Add medication</Button>} /><Panel><div className="border-b p-4"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search code, brand, or generic name" /></div>{query.isLoading ? <LoadingPanel /> : query.isError || !query.data ? <ErrorPanel message={query.error?.message} /> : query.data.items.length ? <DataTable headers={["Code", "Medication", "Category", "Form / strength", "Stock", "Reorder", "Status", "Action"]}>{query.data.items.map((item) => <MedicationRow key={item.id} item={item} />)}</DataTable> : <EmptyState title="No medications found" description="Create the first facility medication record." />}</Panel><Modal title="Add medication" open={open} onClose={() => setOpen(false)}><form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><Field label="Code"><Input value={form.code ?? ""} onChange={(event) => setForm({ ...form, code: event.target.value || null })} /></Field><Field label="Medication name"><Input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="Generic name"><Input value={form.genericName ?? ""} onChange={(event) => setForm({ ...form, genericName: event.target.value || null })} /></Field><Field label="Category"><Input value={form.category ?? ""} onChange={(event) => setForm({ ...form, category: event.target.value || null })} /></Field><Field label="Dosage form"><Input value={form.dosageForm ?? ""} onChange={(event) => setForm({ ...form, dosageForm: event.target.value || null })} /></Field><Field label="Strength"><Input value={form.strength ?? ""} onChange={(event) => setForm({ ...form, strength: event.target.value || null })} /></Field><Field label="Unit"><Input value={form.unit ?? ""} onChange={(event) => setForm({ ...form, unit: event.target.value || null })} /></Field><Field label="Reorder level"><Input type="number" min={0} value={form.reorderLevel} onChange={(event) => setForm({ ...form, reorderLevel: Number(event.target.value) })} /></Field><div className="sm:col-span-2"><ErrorMessage error={create.error} /><div className="mt-3 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={create.isPending}>{create.isPending ? "Saving..." : "Save medication"}</Button></div></div></form></Modal></>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium">{label}<span className="mt-1 block">{children}</span></label> }
function MedicationRow({ item }: { item: MedicationCatalogItem }) { const update = useUpdateMedication(item.id); return <tr><td className={td}>{item.code ?? "—"}</td><td className={td}><p className="font-semibold">{item.name}</p><p className="text-xs text-muted-foreground">{item.genericName ?? "—"}</p></td><td className={td}>{item.category ?? "—"}</td><td className={td}>{[item.dosageForm, item.strength].filter(Boolean).join(" · ") || "—"}</td><td className={td}>{item.stockQuantity}</td><td className={td}>{item.reorderLevel}</td><td className={td}><StatusBadge value={item.isActive ? "AVAILABLE" : "INACTIVE"} /></td><td className={td}><Button variant="outline" size="sm" disabled={update.isPending} onClick={() => update.mutate({ isActive: !item.isActive })}>{item.isActive ? "Deactivate" : "Activate"}</Button></td></tr> }

export function StockPage() {
  const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [selected, setSelected] = useState<MedicationStockItem | null>(null); const [damaged, setDamaged] = useState<MedicationStockItem | null>(null)
  const [form, setForm] = useState({ medicationId: "", batchNumber: "", expiryDate: "", quantityOnHand: 0, unitCost: "", sellingPrice: "", reference: "" })
  const query = useStock({ search, pageSize: 100 }); const medications = useMedications({ active: true, pageSize: 100 }); const create = useCreateStock()
  async function submit(event: React.FormEvent) { event.preventDefault(); await create.mutateAsync({ medicationId: form.medicationId, batchNumber: form.batchNumber || null, expiryDate: form.expiryDate ? new Date(`${form.expiryDate}T00:00:00`).toISOString() : null, quantityOnHand: Number(form.quantityOnHand), unitCost: form.unitCost ? Number(form.unitCost) : null, sellingPrice: form.sellingPrice ? Number(form.sellingPrice) : null, reference: form.reference || null }); setOpen(false) }
  return <><PageHeader title="Medicine stock" description="Facility batches, balances, pricing, expiry, and immutable movement corrections." actions={<Button onClick={() => setOpen(true)}><PackagePlus />Receive stock batch</Button>} /><Panel><div className="border-b p-4"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search medicine or batch" /></div>{query.isLoading ? <LoadingPanel /> : query.isError || !query.data ? <ErrorPanel message={query.error?.message} /> : query.data.items.length ? <DataTable headers={["Medicine", "Batch", "Expiry", "On hand", "Reorder", "Unit cost", "Price", "Status", "Actions"]}>{query.data.items.map((stock) => <tr key={stock.id}><td className={td}><p className="font-semibold">{stock.medicationName}</p><p className="text-xs text-muted-foreground">{stock.genericName ?? "—"}</p></td><td className={td}>{stock.batchNumber ?? "—"}</td><td className={td}>{formatDate(stock.expiryDate)}</td><td className={td}><strong>{stock.quantityOnHand}</strong></td><td className={td}>{stock.reorderLevel}</td><td className={td}>{money(stock.unitCost)}</td><td className={td}>{money(stock.sellingPrice)}</td><td className={td}><StatusBadge value={stock.stockStatus} /></td><td className={td}><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => setSelected(stock)}><RotateCcw />Movement</Button><Button variant="outline" size="sm" disabled={!stock.quantityOnHand} onClick={() => setDamaged(stock)}>Damage</Button></div></td></tr>)}</DataTable> : <EmptyState title="No stock batches" description="Receive the first facility stock batch." />}</Panel>
    <Modal title="Receive stock batch" open={open} onClose={() => setOpen(false)}><form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><Field label="Medication"><select required className={controlClass} value={form.medicationId} onChange={(event) => setForm({ ...form, medicationId: event.target.value })}><option value="">Select medication</option>{medications.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}{item.strength ? ` · ${item.strength}` : ""}</option>)}</select></Field><Field label="Batch number"><Input value={form.batchNumber} onChange={(event) => setForm({ ...form, batchNumber: event.target.value })} /></Field><Field label="Expiry date"><Input type="date" value={form.expiryDate} onChange={(event) => setForm({ ...form, expiryDate: event.target.value })} /></Field><Field label="Opening quantity"><Input required type="number" min={0} value={form.quantityOnHand} onChange={(event) => setForm({ ...form, quantityOnHand: Number(event.target.value) })} /></Field><Field label="Unit cost (GHS)"><Input type="number" min={0} step="0.01" value={form.unitCost} onChange={(event) => setForm({ ...form, unitCost: event.target.value })} /></Field><Field label="Selling price (GHS)"><Input type="number" min={0} step="0.01" value={form.sellingPrice} onChange={(event) => setForm({ ...form, sellingPrice: event.target.value })} /></Field><Field label="Reference"><Input value={form.reference} onChange={(event) => setForm({ ...form, reference: event.target.value })} /></Field><div className="sm:col-span-2"><ErrorMessage error={create.error} /><div className="mt-3 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={create.isPending}>{create.isPending ? "Saving..." : "Create stock batch"}</Button></div></div></form></Modal>
    {selected ? <MovementModal stock={selected} close={() => setSelected(null)} /> : null}
    {damaged ? <WriteOffModal stock={damaged} kind="damaged" close={() => setDamaged(null)} /> : null}
  </>
}
function MovementModal({ stock, close }: { stock: MedicationStockItem; close: () => void }) { const mutation = useCreateMovement(stock.id); const [form, setForm] = useState({ type: "ADJUSTMENT_IN", quantity: 1, reason: "", reference: "" }); async function submit(event: React.FormEvent) { event.preventDefault(); await mutation.mutateAsync({ type: form.type as never, quantity: Number(form.quantity), reason: form.reason, reference: form.reference || null }); close() } return <Modal title={`Record movement · ${stock.medicationName}`} open onClose={close}><form className="space-y-4" onSubmit={submit}><p className="rounded bg-orange-50 p-3 text-sm text-orange-900">Generic movements cannot fabricate dispensing, expiry, damage, or opening balances. Corrections are appended, never edited.</p><Field label="Movement type"><select className={controlClass} value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="PURCHASE">Purchase</option><option value="DONATION">Donation</option><option value="TRANSFER_IN">Transfer in</option><option value="TRANSFER_OUT">Transfer out</option><option value="ADJUSTMENT_IN">Adjustment in</option><option value="ADJUSTMENT_OUT">Adjustment out</option></select></Field><Field label="Quantity"><Input type="number" min={1} required value={form.quantity} onChange={(event) => setForm({ ...form, quantity: Number(event.target.value) })} /></Field><Field label="Reason"><Input required value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></Field><Field label="Reference"><Input value={form.reference} onChange={(event) => setForm({ ...form, reference: event.target.value })} /></Field><ErrorMessage error={mutation.error} /><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={close}>Close</Button><Button type="submit" disabled={mutation.isPending}>Record movement</Button></div></form></Modal> }

export function LowStockPage() { const query = useLowStock(); const [selected, setSelected] = useState<(MedicationStockItem & { recommendedQuantity: number }) | null>(null); return <><PageHeader title="Low-stock alerts" description="Deduplicated facility batch alerts and lightweight reorder tracking." />{query.isLoading ? <LoadingPanel /> : query.isError || !query.data ? <ErrorPanel message={query.error?.message} /> : <Panel>{query.data.length ? <DataTable headers={["Medicine", "Batch", "On hand", "Reorder level", "Shortage", "Reorder", "Action"]}>{query.data.map((stock) => <tr key={stock.id}><td className={td}>{stock.medicationName}</td><td className={td}>{stock.batchNumber ?? "—"}</td><td className={td}><strong className="text-red-700">{stock.quantityOnHand}</strong></td><td className={td}>{stock.reorderLevel}</td><td className={td}>{stock.shortageAmount}</td><td className={td}>{stock.activeReorder ? <StatusBadge value={String(stock.activeReorder.status)} /> : "—"}</td><td className={td}>{stock.activeReorder ? <ReorderStateControl reorder={stock.activeReorder as { id: string; status: string }} /> : <Button size="sm" onClick={() => setSelected(stock)}><Plus />Request reorder</Button>}</td></tr>)}</DataTable> : <EmptyState title="No low-stock alerts" description="Resolved alerts are archived automatically when a batch recovers." />}</Panel>}{selected ? <ReorderModal stock={selected} close={() => setSelected(null)} /> : null}</> }
function ReorderModal({ stock, close }: { stock: MedicationStockItem & { recommendedQuantity: number }; close: () => void }) { const mutation = useCreateReorder(stock.id); const [quantity, setQuantity] = useState(stock.recommendedQuantity); const [notes, setNotes] = useState(""); async function submit(event: React.FormEvent) { event.preventDefault(); await mutation.mutateAsync({ requestedQuantity: quantity, notes: notes || null }); close() } return <Modal title={`Request reorder · ${stock.medicationName}`} open onClose={close}><form className="space-y-4" onSubmit={submit}><Field label="Requested quantity"><Input required type="number" min={1} value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /></Field><Field label="Notes"><textarea className={controlClass} value={notes} onChange={(event) => setNotes(event.target.value)} /></Field><ErrorMessage error={mutation.error} /><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={close}>Close</Button><Button type="submit" disabled={mutation.isPending}>Create request</Button></div></form></Modal> }
function ReorderStateControl({ reorder }: { reorder: { id: string; status: string } }) { const mutation = useUpdateReorder(reorder.id); const next = reorder.status === "REQUESTED" ? "ORDERED" : reorder.status === "ORDERED" ? "RECEIVED" : null; return next ? <Button size="sm" variant="outline" disabled={mutation.isPending} onClick={() => mutation.mutate({ status: next })}>Mark {next.toLowerCase()}</Button> : null }

export function ExpiredStockPage() { const query = useExpiredStock(); const [selected, setSelected] = useState<MedicationStockItem | null>(null); return <><PageHeader title="Expiry management" description="Expired medicines and batches expiring within 30 days. Write-offs create immutable stock movements." />{query.isLoading ? <LoadingPanel /> : query.isError || !query.data ? <ErrorPanel message={query.error?.message} /> : <Panel>{query.data.length ? <DataTable headers={["Medicine", "Batch", "Expiry", "On hand", "Expiry state", "Disposal", "Action"]}>{query.data.map((stock) => <tr key={stock.id}><td className={td}>{stock.medicationName}</td><td className={td}>{stock.batchNumber ?? "—"}</td><td className={td}>{formatDate(stock.expiryDate)}</td><td className={td}>{stock.quantityOnHand}</td><td className={td}><StatusBadge value={stock.expiryStatus} /></td><td className={td}><StatusBadge value={stock.disposalStatus} /></td><td className={td}><Button variant="destructive" size="sm" disabled={!stock.quantityOnHand || stock.expiryStatus !== "EXPIRED"} onClick={() => setSelected(stock)}><TriangleAlert />Record expired</Button></td></tr>)}</DataTable> : <EmptyState title="No expiry risks" description="No stock is expired or within the 30-day review window." />}</Panel>}{selected ? <WriteOffModal stock={selected} kind="expired" close={() => setSelected(null)} /> : null}</> }
function WriteOffModal({ stock, kind, close }: { stock: MedicationStockItem; kind: "expired" | "damaged"; close: () => void }) { const mutation = useWriteOffStock(stock.id, kind); const [quantity, setQuantity] = useState(stock.quantityOnHand); const [reason, setReason] = useState(""); async function submit(event: React.FormEvent) { event.preventDefault(); await mutation.mutateAsync({ quantity, reason }); close() } return <Modal title={`Record ${kind} stock · ${stock.medicationName}`} open onClose={close}><form className="space-y-4" onSubmit={submit}><p className="rounded bg-orange-50 p-3 text-sm text-orange-900">This creates an immutable {kind} movement and immediately reduces the usable batch balance.</p><Field label="Quantity"><Input type="number" min={1} max={stock.quantityOnHand} value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /></Field><Field label="Reason"><textarea required className={controlClass} value={reason} onChange={(event) => setReason(event.target.value)} /></Field><ErrorMessage error={mutation.error} /><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={close}>Close</Button><Button type="submit" variant="destructive" disabled={mutation.isPending}>Record write-off</Button></div></form></Modal> }

export function StockMovementsPage() { const [search, setSearch] = useState(""); const [type, setType] = useState(""); const query = useStockMovements({ search, type, pageSize: 100 }); return <><PageHeader title="Stock movements" description="Append-only batch ledger with reversal linkage and actor traceability." /><Panel><div className="grid gap-3 border-b p-4 sm:grid-cols-[1fr_220px]"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search medication, batch, or reference" /><select className={controlClass} value={type} onChange={(event) => setType(event.target.value)}><option value="">All movement types</option>{["OPENING_BALANCE", "PURCHASE", "DONATION", "DISPENSE", "TRANSFER_IN", "TRANSFER_OUT", "ADJUSTMENT_IN", "ADJUSTMENT_OUT", "EXPIRED", "DAMAGED"].map((value) => <option key={value}>{value}</option>)}</select></div>{query.isLoading ? <LoadingPanel /> : query.isError || !query.data ? <ErrorPanel message={query.error?.message} /> : query.data.items.length ? <DataTable headers={["Medicine", "Batch", "Type", "Quantity", "Reason", "Reference", "Actor", "Recorded"]}>{query.data.items.map((movement) => <tr key={movement.id}><td className={td}>{movement.medicationName}</td><td className={td}>{movement.batchNumber ?? "—"}</td><td className={td}><StatusBadge value={movement.type} /></td><td className={td}>{movement.quantity}</td><td className={td}>{movement.reason ?? "—"}</td><td className={td}>{movement.reference ?? "—"}</td><td className={td}>{movement.performedByName ?? "—"}</td><td className={td}>{formatDate(movement.createdAt)}</td></tr>)}</DataTable> : <EmptyState title="No stock movements" description="Movements appear when stock is received, adjusted, dispensed, or written off." />}</Panel></> }

